import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import productsRouter from "./products.js";
import ordersRouter from "./orders.js";
import customersRouter from "./customers.js";
import marketingRouter from "./marketing.js";
import analyticsRouter from "./analytics.js";
import cartRouter from "./cart.js";
import specialCollectionsRouter from "./specialCollections.js";
import authRouter from "./auth.js";
import bannersRouter from "./banners.js";
import storiesRouter from "./stories.js";
import contentRouter from "./content.js";
import notificationsRouter from "./notifications.js";
import waylRouter from "./wayl.js";
import adminAuthRouter from "./admin-auth.js";
import webhooksRouter from "./webhooks.js";
import uploadsRouter from "./uploads.js";
import shippingRouter from "./shipping.js";
import chatAdminRouter from "./chat-admin.js";
import chatPublicRouter from "./chat-public.js";
import browseCollectionsRouter from "./browseCollections.js";
import saleCollectionsRouter from "./saleCollections.js";

const router: IRouter = Router();

router.use(uploadsRouter);
router.use(healthRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(waylRouter);
router.use(adminAuthRouter);
router.use(customersRouter);
router.use(marketingRouter);
router.use(analyticsRouter);
router.use(cartRouter);
router.use(specialCollectionsRouter);
router.use(browseCollectionsRouter);
router.use(saleCollectionsRouter);
router.use(authRouter);
router.use(bannersRouter);
router.use(storiesRouter);
router.use(contentRouter);
router.use(notificationsRouter);
router.use(webhooksRouter);
router.use(shippingRouter);
router.use(chatAdminRouter);
router.use("/chat", chatPublicRouter);

export default router;
