-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIgJzeWLKoPtzUjQg
I+l2MvrO1O8JLPYAZwhzBygQ50ugCgYIKoZIzj0DAQehRANCAAQGU+ipgdoZJf65
/42JKKmqPo6LOK7xsHI4dmXm/v62NWsD3KHpH5PV4bYUVeqU4neSZBaPYHmOClsg
PCKgdnbM
-----END PRIVATE KEY-----